services:
  db:
    image: postgres:16
    command: ["postgres", "-p", "5434"]
    restart: always
    environment:
      POSTGRES_DB: ${DbSettings__Database}
      POSTGRES_USER: ${DbSettings__Username}
      POSTGRES_PASSWORD: ${DbSettings__Password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "55433:5434"

  transaction-service:
    build:
      context: .
      dockerfile: FinanceManager.TransactionsService.API/Dockerfile
    depends_on:
      - db
    ports:
      - "8082:8082"
      - "8083:8083"
      - "5024:5024"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      DbSettings__Host: db
      DbSettings__Port: ${DbSettings__Port}
      DbSettings__Database: ${DbSettings__Database}
      DbSettings__Username: ${DbSettings__Username}
      DbSettings__Password: ${DbSettings__Password}
      ASPNETCORE_HTTP_PORTS: ${ASPNETCORE_HTTP_PORTS}
    restart: always

volumes:
  postgres_data:
