services:
  csdb:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${FmcsDbSettings__Database}
      POSTGRES_USER: ${FmcsDbSettings__Username}
      POSTGRES_PASSWORD: ${FmcsDbSettings__Password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "55432:5432"
    networks:
      - financemanager_common_net

  catalog-service:
    build:
      context: .
      dockerfile: FinanceManager.CatalogService.API/Dockerfile
    depends_on:
      - csdb
    ports:
      - "8080:8080"
      - "8081:8081"
      - "5023:5023"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      FmcsDbSettings__Host: csdb
      FmcsDbSettings__Port: "5432"
      FmcsDbSettings__Database: ${FmcsDbSettings__Database}
      FmcsDbSettings__Username: ${FmcsDbSettings__Username}
      FmcsDbSettings__Password: ${FmcsDbSettings__Password}
    restart: always
    networks:
      - financemanager_common_net

volumes:
  postgres_data:
    
networks:
  financemanager_common_net:
    external: true
