services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${FmcsDbSettings__Database}
      POSTGRES_USER: ${FmcsDbSettings__Username}
      POSTGRES_PASSWORD: ${FmcsDbSettings__Password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "55432:5432"

  catalog-service:
    build:
      context: .
      dockerfile: FinanceManager.CatalogService.API/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8081:8081"
      - "5023:5023"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      FmcsDbSettings__Host: db
      FmcsDbSettings__Port: "5432"
      FmcsDbSettings__Database: ${FmcsDbSettings__Database}
      FmcsDbSettings__Username: ${FmcsDbSettings__Username}
      FmcsDbSettings__Password: ${FmcsDbSettings__Password}
    restart: always

volumes:
  postgres_data:
